### ISSUE TITLE
how to run it on windows?

### ISSUE THREAD

**Issue by ddatsh** [neerolyte/repoproxy#4]
cd /d d:\
git clone  https://github.com/neerolyte/repoproxy.git
downloaded   precise32.box ,move to  d:\repoproxy

modify Vagrantfile
config.vm.box_url = "http://files.vagrantup.com/precise32.box"
config.vm.box_url = "precise32.box"

D:\repoproxy>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'precise32'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: repoproxy_default_1411719714568_10008
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'poweroff' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

and ?

**Comment by neerolyte** [comment]
Hi ddatsh, repoproxy is just a NodeJS program so you should be able to run it with `node repoproxy.js` after installing the dependencies (`npm install`).

I'm just using Vagrant to get a consistent development environment.

I should warn you that although it is possible it use repoproxy now with some package managers, it's not really ready for prime time yet (needs work around doco, running as a proper service and better default config).
